export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export DATA_DIR='/data/kcl/lpy/data'
WAND_PROJECT="self_critic"
export SWANLAB_API_KEY="DDMUFxYQU6Om1ZuHWYoxm"           # 设置在线跟踪模式API
export BASE_MODEL='/data/kcl/lpy/models/Qwen2_5_3B_Instruct'
export EXPERIMENT_NAME=origin_gsm8k_qwen2_5b_instruct
N_NODES=1
n_gpus_per_node=8
export BASE_DIR=$(pwd)
export HF_ENDPOINT=https://hf-mirror.com
export VLLM_USE_V1=1
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=$DATA_DIR/gsm8k/train.parquet \
 data.val_files=$DATA_DIR/gsm8k/test.parquet \
 data.train_batch_size=256 \
 data.max_prompt_length=512 \
 data.max_response_length=512 \
 actor_rollout_ref.model.path=$BASE_MODEL \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=64 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-5 \
 critic.model.path=$BASE_MODEL \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.logger=console \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=$n_gpus_per_node \
 trainer.nnodes=$N_NODES \
 trainer.save_freq=10 \
 trainer.test_freq=10 \
 trainer.logger="['swanlab', 'console']" \
 trainer.project_name=$WAND_PROJECT \
 trainer.experiment_name=$EXPERIMENT_NAME \
 trainer.total_epochs=15 2>&1 | tee verl_log/$EXPERIMENT_NAME.log