export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export DATA_DIR='/data/kcl/lpy/data'
WAND_PROJECT="self_reflect"
export SWANLAB_API_KEY="DDMUFxYQU6Om1ZuHWYoxm"           # 设置在线跟踪模式API
export BASE_MODEL='/data/kcl/lpy/models/qwen3_4b_instruct'
export TEACHER_MODEL='/data/kcl/lpy/models/qwen3_4b_instruct'
export EXPERIMENT_NAME=teacher_student_dapo_qwen3_4b_instruct_alleval
N_NODES=1
n_gpus_per_node=8
export BASE_DIR=$(pwd)
export HF_ENDPOINT=https://hf-mirror.com
export VLLM_USE_V1=1
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_self_reflective \
 data.train_files=$DATA_DIR/dapo/train_verl.parquet \
 data.val_files=[$DATA_DIR/AIME_2024/test_verl.parquet,$DATA_DIR/AIME_2025/test_verl.parquet,$DATA_DIR/HMMT_FEB_2025/test_verl.parquet] \
 data.train_batch_size=224 \
 data.max_prompt_length=1024 \
 data.max_response_length=1024 \
 +data.summary_max_new_tokens=1024 \
 +teacher.model.path=$TEACHER_MODEL \
 +teacher.rollout.tensor_model_parallel_size=1 \
 +teacher.rollout.gpu_memory_utilization=0.8 \
 actor_rollout_ref.model.path=$BASE_MODEL \
 +actor_rollout_ref.model.torch_dtype=bfloat16 \
 actor_rollout_ref.actor.optim.lr=5e-7 \
 actor_rollout_ref.actor.ppo_mini_batch_size=56 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.actor.policy_loss=distillation \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
 actor_rollout_ref.rollout.max_num_batched_tokens=8000 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
 critic.optim.lr=1e-5 \
 critic.model.path=$BASE_MODEL \
 critic.ppo_micro_batch_size_per_gpu=1 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.logger=console \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=$n_gpus_per_node \
 trainer.nnodes=$N_NODES \
 trainer.save_freq=30 \
 trainer.test_freq=30 \
 trainer.logger="['swanlab', 'console']" \
 trainer.project_name=$WAND_PROJECT \
 trainer.experiment_name=$EXPERIMENT_NAME \
 trainer.default_local_dir=${BASE_DIR}/verl_checkpoints/$EXPERIMENT_NAME \
 trainer.total_epochs=15 2>&1 | tee verl_log/$EXPERIMENT_NAME.log