export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export DATA_DIR='/data/kcl/lpy/data'
WAND_PROJECT="self_reflect"
export SWANLAB_API_KEY="DDMUFxYQU6Om1ZuHWYoxm"           # 设置在线跟踪模式API
export BASE_MODEL='/data/kcl/lpy/models/qwen3_4b_instruct'
export EXPERIMENT_NAME=grpo_deepscale_qwen3_4b_instruct_alleval
N_NODES=1
n_gpus_per_node=8
export BASE_DIR=$(pwd)
export HF_ENDPOINT=https://hf-mirror.com
export VLLM_USE_V1=1
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
export TORCH_DTYPE=bfloat16
train_batch_size=$[$n_gpus_per_node * 64]
actor_ppo_mini_batch_size=$[$n_gpus_per_node * 8]
actor_ppo_micro_batch_size=$[$n_gpus_per_node * 4]
log_prob_micro_batch_size=$[$n_gpus_per_node * 4]
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=$DATA_DIR/deepscale_r/train_verl.parquet \
 data.val_files=[$DATA_DIR/AIME_2024/test_verl.parquet,$DATA_DIR/AIME_2025/test_verl.parquet,$DATA_DIR/HMMT_FEB_2025/test_verl.parquet] \
 data.train_batch_size=$train_batch_size \
 data.max_prompt_length=4096 \
 data.max_response_length=4096 \
 +data.summary_max_new_tokens=4096 \
 algorithm.adv_estimator=grpo \
 actor_rollout_ref.model.path=$BASE_MODEL \
 actor_rollout_ref.actor.optim.lr=5e-7 \
 actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.5 \
 actor_rollout_ref.actor.ppo_mini_batch_size=$actor_ppo_mini_batch_size \
 actor_rollout_ref.actor.ppo_micro_batch_size=$actor_ppo_micro_batch_size \
 actor_rollout_ref.actor.use_kl_loss=true \
 +actor_rollout_ref.actor.fsdp_config.model_dtype=bfloat16 \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.actor.kl_loss_coef=0.01 \
 actor_rollout_ref.actor.kl_loss_type=low_var_kl \
 actor_rollout_ref.rollout.n=5 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 algorithm.use_kl_in_reward=False \
 trainer.critic_warmup=0 \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=$n_gpus_per_node \
 trainer.nnodes=$N_NODES \
 trainer.save_freq=30 \
 trainer.test_freq=30 \
 trainer.logger="['swanlab', 'console']" \
 trainer.project_name=$WAND_PROJECT \
 trainer.experiment_name=$EXPERIMENT_NAME \
 trainer.default_local_dir=${BASE_DIR}/verl_checkpoints/$EXPERIMENT_NAME \
 trainer.total_epochs=15 2>&1 | tee verl_log/$EXPERIMENT_NAME.log